### ISSUE TITLE
security repository

### ISSUE THREAD

**Issue by kruptworld** [beli3ver/debgen#1]
i had to add "debian-security" after "deb ftp://security.debian.org/" for it to resolve correctly.

A side note, I'm knew to setting up debian, so I don't know if this had anything to do on my end. I couldn't resolve anything until I added "nameserver 8.8.8.8 nameserver 8.8.4.4" to resolv.conf and also changed all the "http"s to "ftp" in the links provided by the generator for it all to resolve correctly.

**Comment by beli3ver** [comment]
Sorry for my late answer :-)

https://www.debian.org/security/

Here it means you must use it like this:

`deb http://security.debian.org/ jessie/updates main contrib non-free`

It looks like you have a big DNS problem with your router.

**Comment by MindTooth** [comment]
```
deb http://deb.debian.org/debian-**secruity** stable/updates main
deb-src http://deb.debian.org/debian-**secruity** stable/updates main
```

Should be `security` and not `secruity` ;-)
