### ISSUE TITLE
api access  

### ISSUE THREAD

**Issue by silent-mobius** [beli3ver/debgen#10]
is it possible to access api with python to get the repo with specific requests?
for example - ask for source-list  request for debian jessie via api.
if not - with php only ?
and most importantly - how?

**Comment by beli3ver** [comment]
This "api" was never developed to get access via python.

**Comment by silent-mobius** [comment]
So how can i get access via script ?

**Comment by beli3ver** [comment]
There is new site coming. There will be a RESTful API.

**Comment by silent-mobius** [comment]
thanks
