### ISSUE TITLE
Error GPG keys Debian stretch

### ISSUE THREAD

**Issue by carlosnewmusic** [beli3ver/debgen#11]
![imagen](https://user-images.githubusercontent.com/19379457/46144229-9822d700-c25c-11e8-921e-42d6fa0b50e5.png)

**Comment by carlosnewmusic** [comment]
![imagen](https://user-images.githubusercontent.com/19379457/46144393-14b5b580-c25d-11e8-8c06-e6d93536960c.png)

**Comment by beli3ver** [comment]
Yes I know.
Lot to do.
Give me please the Repos, with the key erros.

**Comment by carlosnewmusic** [comment]
###### 3rd Party Binary Repos
###Debian Multimedia
deb https://www.deb-multimedia.org stable main non-free

###Lynis
deb https://packages.cisofy.com/community/lynis/deb/ stable main

###MariaDB
deb http://mirror.23media.de/mariadb/repo/10.2/debian stretch main
deb-src http://mirror.23media.de/mariadb/repo/10.2/debian stretch main

###nginx
deb http://nginx.org/packages/debian/ stretch nginx
deb-src http://nginx.org/packages/debian/ stretch nginx

###openmediavault
deb http://packages.openmediavault.org/public erasmus main
deb-src http://packages.openmediavault.org/public erasmus main

###Opera
deb https://deb.opera.com/opera-stable/ stable non-free

###TOR
deb [arch=i386,amd64,armel,armhf] http://deb.torproject.org/torproject.org stable main
deb-src [arch=i386,amd64,armel,armhf] http://deb.torproject.org/torproject.org stable main

###Ubuntuzilla
deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main

###Webmin
deb http://download.webmin.com/download/repository sarge contrib

wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8
wget https://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key
apt-get update && apt-get install openmediavault-keyring && apt-get update
wget -O - http://deb.opera.com/archive.key | apt-key add -
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys D97A3AE911F63C51

**Comment by carlosnewmusic** [comment]
the tor is fixed but the webmin keeps giving the same error

**Comment by beli3ver** [comment]
fixed #11

**Comment by carlosnewmusic** [comment]
El repositorio «http://mozilla.debian.net experimental Release» no tiene un fichero de Publicación.No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.Error de GPG: http://packages.openmediavault.org/public erasmus InRelease: Las firmas siguientes no se pudieron verificar porque su clave pública no está disponible: NO_PUBKEY 7E7A6C592EF35D13 NO_PUBKEY 24863F0C716B980BEl repositorio «http://packages.openmediavault.org/public erasmus InRelease» no está firmado.No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.Error de GPG: http://linux-packages.resilio.com/resilio-sync/deb resilio-sync InRelease: Las firmas siguientes no se pudieron verificar porque su clave pública no está disponible: NO_PUBKEY BE66CC4C3F171DE2El repositorio «http://linux-packages.resilio.com/resilio-sync/deb resilio-sync InRelease» no está firmado.No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.Error de GPG: https://repo.skype.com/deb stable InRelease: Las firmas siguientes no se pudieron verificar porque su clave pública no está disponible: NO_PUBKEY 1F3045A5DF7587C3El repositorio «https://repo.skype.com/deb stable InRelease» no está firmado.

repos
#------------------------------------------------------------------------------#
#                   OFFICIAL DEBIAN REPOS                    
#------------------------------------------------------------------------------#

###### Debian Main Repos
deb http://deb.debian.org/debian/ testing main contrib non-free
deb-src http://deb.debian.org/debian/ testing main contrib non-free

deb http://deb.debian.org/debian/ testing-updates main contrib non-free
deb-src http://deb.debian.org/debian/ testing-updates main contrib non-free

deb http://deb.debian.org/debian-security testing/updates main
deb-src http://deb.debian.org/debian-security testing/updates main

#------------------------------------------------------------------------------#
#                      UNOFFICIAL  REPOS                       
#------------------------------------------------------------------------------#

###### 3rd Party Binary Repos
###Debian Multimedia
deb [arch=amd64,i386] http://www.deb-multimedia.org buster main non-free

###Ghostwriter
deb http://ppa.launchpad.net/wereturtle/ppa/ubuntu bionic main 
deb-src http://ppa.launchpad.net/wereturtle/ppa/ubuntu bionic main

###Google Chrome Browser
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

###Google Earth
deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main

###Lynis
deb https://packages.cisofy.com/community/lynis/deb/ stable main

###Mozilla Firefox Aurora
deb http://mozilla.debian.net/ experimental firefox-aurora

###Nextcloud Client
deb [arch=amd64,i386] http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/ /

###nginx
deb [arch=amd64,i386] http://nginx.org/packages/debian/ stretch nginx
deb-src [arch=amd64,i386] http://nginx.org/packages/debian/ stretch nginx

###openmediavault
deb http://packages.openmediavault.org/public erasmus main
deb-src http://packages.openmediavault.org/public erasmus main

###Opera
deb [arch=amd64,i386] https://deb.opera.com/opera-stable/ stable non-free

###Resilio Sync
deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free

###Skype
deb [arch=amd64] https://repo.skype.com/deb stable main

###Spotify
deb http://repository.spotify.com stable non-free

###Steam
deb [arch=i386,amd64] http://repo.steampowered.com/steam/ precise steam

###Teamviewer
deb http://linux.teamviewer.com/deb stable main

###TOR
deb [arch=i386,amd64,armel,armhf] http://deb.torproject.org/torproject.org testing main
deb-src [arch=i386,amd64,armel,armhf] http://deb.torproject.org/torproject.org testing main

###Ubuntuzilla
deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main

###Visual Studio Code
deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb && dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys EF3F38C8FD5E1EE2E7B3B657653124679B3CCB19
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 85A3D26506C4AE2A
wget -q -O - http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/Release.key | apt-key add -
wget https://nginx.org/keys/nginx_signing.key && apt-key add nginx_signing.key
apt-get update && apt-get install openmediavault-keyring && apt-get update
wget -O - http://deb.opera.com/archive.key | apt-key add -
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 05CD43032484414B
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 1F3045A5DF7587C3
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys A87FF9DF48BF1C90
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F24AEA9FB05498B7
wget -O - https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc | apt-key add -
apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 74A941BA219EC810
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2667CA5C
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
