### ISSUE TITLE
Seems file is missing

### ISSUE THREAD

**Issue by lol-deb** [beli3ver/debgen#13]
Hello,
I'm trying to install debgen on my own machine, but it seems a file (at least) is missing:

`Got error 'PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(../../class/class.repo.php) is not within the allowed path(s): (/var/www/clients/client0/web10/web:/var/www/clients/client0/web10/private:/var/www/clients/client0/web10/tmp:/var/www/xxx/web:/srv/www/xxx/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom) in /var/www/clients/client0/web10/web/debgen/config/config.php on line 30\nPHP message: PHP Fatal error:  Uncaught Error: Class 'Repo' not found in /var/www/clients/client0/web10/web/debgen/index.php:6\nStack trace:\n#0 {main}\n  thrown in /var/www/clients/client0/web10/web/debgen/index.php on line 6\n'`

Do you know why class.repo.php file is missing ? I can't find it in the github repo.
Thank you.

**Comment by beli3ver** [comment]
Hi.
Sorry I have seen that here is not the latest version from debgen.
I will to get upload the latest in the next days.
Sorry for that.

**Comment by lol-deb** [comment]
Hello,
Please, don't be sorry, you just forget to update.
Your debgen is very helpful. I was using a very late version, but the new one seems very promising!
I'm waiting for your update.

**Comment by lol-deb** [comment]
Hello @beli3ver,
You'll think upload the updates and missing files ?
Thank you.
Laurent.

**Comment by lol-deb** [comment]
Hello @beli3ver,
Some update?
Thanks.

**Comment by lol-deb** [comment]
Hello @beli3ver 
Some news ?
thks.

**Comment by beli3ver** [comment]
I pushed all files, sorry that it needed so long

**Comment by lol-deb** [comment]
Great,
Thank you very much!
