### ISSUE TITLE
error with testing/security

### ISSUE THREAD

**Issue by xxKeith20xx** [beli3ver/debgen#14]
Getting the following error on testing and seeing that http://deb.debian.org/debian-security is invalid now since the release of Buster:

```
Err:8 http://deb.debian.org/debian-security testing/updates Release
  404  Not Found [IP: 151.101.136.204 80]
[...]
Reading package lists... Done
E: The repository 'http://deb.debian.org/debian-security testing/updates Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by beli3ver** [comment]
I am currently working on a new version.
Sorry for the delay

**Comment by xxKeith20xx** [comment]
Looks like testing/updates should be testing-security now for http://security.debian.org:
https://unix.stackexchange.com/questions/528751/cannot-update-apt-list-repository-no-longer-has-a-release-file

**Comment by beli3ver** [comment]
Done
