### ISSUE TITLE
Debian Testing (Stretch) repos don't work

### ISSUE THREAD

**Issue by Alkaris** [beli3ver/debgen#2]
A friend recommended this list but as I went to add them and add their keys too, but their GPG keys are either broken or not valid anymore, plus repos would hit Error 404 because it can't find what it's pointed to.

![shutter__2017yyy_ 8_04-08-17__10_29_22_pm](https://cloud.githubusercontent.com/assets/6682988/24829184/5cbeb690-1cac-11e7-9b08-d3d6fbdf41f0.png)

**Comment by beli3ver** [comment]
Hello,

you must dircetly add the file

/etc/apt/sources.list



Am 8. April 2017 15:11:37 MESZ schrieb Alkaris <notifications@github.com>:
>A friend recommended this list but as I went to add them and add their
>keys too, but their GPG keys are either broken or not valid anymore,
>plus repos would hit Error 404 because it can't find what it's pointed
>to.
>
>![shutter__2017yyy_
>8_04-08-17__10_29_22_pm](https://cloud.githubusercontent.com/assets/6682988/24829184/5cbeb690-1cac-11e7-9b08-d3d6fbdf41f0.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/debgen/issues/2

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Alkaris** [comment]
I tried this, it doesn't work.

**Comment by beli3ver** [comment]
Post this file here
And the output Form

gpg --list-keys

Am 8. April 2017 15:40:59 MESZ schrieb Alkaris <notifications@github.com>:
>I tried this, it doesn't work.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/debgen/issues/2#issuecomment-292718820

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Alkaris** [comment]
Don't have a file, and there's no output.

**Comment by beli3ver** [comment]
Ok fixed it. Thanks
