### ISSUE TITLE
Unable to unfold the mirror selection

### ISSUE THREAD

**Issue by Tyrben** [beli3ver/debgen#3]
On the website https://debgen.simplylinux.ch/, the field Mirror is a HTML select.

This select has an attribute `disabled=""`.

This cause the select unable to open. It is blocking.

`<select name="country" id="country" disabled="">…</select>`

Because I have Firefox, I can edit the html source on the fly and erase this attribut, then it works.

I looked quickly through the code, and it seems to come from `jquery.js` .

**Comment by beli3ver** [comment]
No
Unckeck the radio box for DEB.Debian.org and it will go

Am 16. April 2017 17:55:40 MESZ schrieb Tyrben <notifications@github.com>:
>On the website https://debgen.simplylinux.ch/, the field Mirror is a
>HTML select.
>
>This select has an attribute `disabled=""`.
>
>This cause the select unable to open. It is blocking.
>
>`<select name="country" id="country" disabled="">…</select>`
>
>Because I have Firefox, I can edit the html source on the fly and erase
>this attribut, then it works.
>
>I looked quickly through the code, and it seems to come from
>`jquery.js` .
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/debgen/issues/3

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
