### ISSUE TITLE
DataBases

### ISSUE THREAD

**Issue by SlaSerX** [beli3ver/debgen#4]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gen.deb_release' doesn't exist SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gen.lastchanges' doesn't exist

Can u upload simple databases

**Comment by beli3ver** [comment]
Hi i will add DB layout

Am 22. April 2017 20:47:10 MESZ schrieb SlaSerX <notifications@github.com>:
>SQLSTATE[42S02]: Base table or view not found: 1146 Table
>'gen.deb_release' doesn't exist SQLSTATE[42S02]: Base table or view not
>found: 1146 Table 'gen.lastchanges' doesn't exist
>
>Can u upload simple databases 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/beli3ver/debgen/issues/4

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by SlaSerX** [comment]
Thx i wait couse now dont have any mirrors and dont work corect :)

**Comment by SlaSerX** [comment]
When upload database couse now script cant use :(
