### ISSUE TITLE
broken links and suggestion

### ISSUE THREAD

**Issue by kompowiec** [beli3ver/debgen#7]
###Adapta GTK Theme
http://ppa.launchpad.net/tista/adapta/ubuntu bionic main
###Docker CE
http://download.docker.com/linux/debian stretch stable

mentioned above error "Failed to read source list.".

simultaneously i proposed add SeaMonkey for this list:
http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt

no need to add a key.

**Comment by beli3ver** [comment]
Ok. I fixed Adapta and added the Repo.
https://debgen.simplylinux.ch/?changes
But for Docker I didn't get a error.

**Comment by beli3ver** [comment]
Ok, my fault.
To fix both erros. add a deb for the http
and by adapta add the second line a deb-src.
Both fixed know in the generator
