### ISSUE TITLE
new feature: installation textbox

### ISSUE THREAD

**Issue by duub** [beli3ver/debgen#9]
Hi,
it would be cool to have a third textbox with the command to install the apps related to the selected 3rd parties repos, because the name of the app comes with some "-word" and would make it faster to find:
`spotify-client signal-desktop owncloud-client`

super nice site! thank you!

**Comment by beli3ver** [comment]
This is lot of work, maybe will find the time

**Comment by duub** [comment]
Just an idea, right now the site is super cool :)
